### ISSUE TITLE
Failed to start load kernel modules on system boot 

### ISSUE THREAD

**Issue by sani1486** [InES-HPMM/linux-l4t-4.9#1]
Hello 
I really appreciate your continuous support for the hdmi2csi hardware. I tried to flash this kernel on my jetson tx2 and flash was successful. however, the system didn't completely boot with an error message 
`Failed to start load kernel modules`
`See 'systemctl status systemd-modules-load-service for details'`
although I can get the video feed from the camera and can access the TX2 system through ssh connection, I can't get to the desktop. 
I am not an expert, so with all the due respect, I have noticed the module folder is named like "4.9.140+ ", I believe in the official l4t it's named as "4.9.140-tegra ". could there be a possibility that modules name caused the issue?

**Comment by weissric** [comment]
Hello
Could you try to copy the firmware folder from the sample root file system located at `Linux_for_Tegra/rootfs/lib/firmware` into the firmware folder of the tx2 `/lib/firmware`.

**Comment by sani1486** [comment]
Thanks for your suggestion, I have figured out what went wrong. I was using the official l4t rootfs firmware instead of the given in this repo.  which caused the problem.
