### ISSUE TITLE
fatal error: linux/tegra_profiler.h: No such file or directory

### ISSUE THREAD

**Issue by fhqddm** [InES-HPMM/linux-l4t-4.9#2]
Hello:

I need to install this  diriver on TX2. I followed the steps of (https://github.com/InES-HPMM/linux-l4t-4.9/wiki/customKernelCompilation). When I execute the command "make Image", the system reports an error("fatal error: linux/tegra_profiler.h: No such file or directory")

How can I fix this?

**Comment by weissric** [comment]
I could not reproduce your problem.

To test, I have downloaded the source code of this repo and set the environment variables as stated in customKernelCompilation you mentioned. 
`export ARCH=arm64` and
`export CROSS_COMPILE=<aarch64_toolchain_prefix>`
Afterwards I have set the defconfigs with
`make tegra18_hdmi2csi_defconfig`
and ran 
`make Image`
Everything executed without error.

Are your submodules correctly checked out?
`git submodule update --init --recursive`
`git submodule foreach --recursive 'git checkout hdmi2csi/l4t-r32.2.1 || :'`
