### ISSUE TITLE
make tegra18_hdmi2csi_defconfig ERROR

### ISSUE THREAD

**Issue by fhqddm** [InES-HPMM/linux-l4t-4.9#3]
drivers/net/ethernet/nvidia/Kconfig:30: can't open file "drivers/net/ethernet/nvidia/eqos/Kconfig"
scripts/kconfig/Makefile:113: recipe for target 'tegra18_hdmi2csi_defconfig' failed
make[1]: *** [tegra18_hdmi2csi_defconfig] Error 1
Makefile:565: recipe for target 'tegra18_hdmi2csi_defconfig' failed
make: *** [tegra18_hdmi2csi_defconfig] Error 2

Actually, I can't find "drivers/net/ethernet/nvidia/eqos/Kconfig" from l4t-4.9-kernel-kernel-4.9.

**Comment by weissric** [comment]
Nvidia has moved some drivers that are Nvidia specific. I think the right location is in the [l4t-4.9-kernel-nvidia](https://github.com/InES-HPMM/l4t-4.9-kernel-nvidia/tree/9c6789e8477ca112fbec2b85c2fde3aa5940b55a) submodule at drivers/net/ethernet/nvidia/eqos/Kconfig. However this should not cause any problems because this folder is included.

Have you pulled the whole [linux-l4t-4.9](https://github.com/InES-HPMM/linux-l4t-4.9) repository with all of its submodules or have you just pulled the l4t-4.9-kernel-kernel-4.9 submodule?

**Comment by fhqddm** [comment]
I just do "make tegra18_hdmi2csi_defconfig" in " l4t-4.9-kernel-kernel-4.9". Do I need to merge “l4t-4.9-kernel-nvidia" in "l4t-4.9-kernel-kernel-4.9" ?

**Comment by weissric** [comment]
You don't need to merge anything. You have to pull the following repository with its submodules:
[linux-l4t-4.9](https://github.com/InES-HPMM/linux-l4t-4.9).
_l4t-4.9-kernel-nvidia_ and _l4t-4.9-kernel-kernel-4.9_ are both submodules of this repository. After pulling the repository, all required files will be present.

Clone the repository and its submodules:
`git clone --recursive https://github.com/InES-HPMM/linux-l4t-4.9.git`

Check out the branch hdmi2csi/l4t-r32.2.1:
`git submodule foreach --recursive 'git checkout hdmi2csi/l4t-r32.2.1 || :'`

You can check if all submodules are checked out the right way with the following command:
`git submodule status --recursive`

after that you can proceed with the steps described in the customKernelCompilation wiki page:
`export ARCH=arm64`
`export CROSS_COMPILE=<aarch64_toolchain_prefix>`
`make tegra18_hdmi2csi_defconfig`
`make Image `
...

**Comment by fhqddm** [comment]
I clone the all project;
cd kernel/kernel-4.9
export ARCH=arm64
(My default gcc version is 5.4.0, so I install a other gcc-4.8)
export CROSS_COMPILE=/usr/bin/aarch64-linux-gnu-gcc-4.8

make tegra18_hdmi2csi_defconfig

and error meesage show a lot of "syntax error":
'ernel/trace/Kconfig:405:warning: ignoring unsupported character '
kernel/trace/Kconfig:405: unknown option "This"
kernel/trace/Kconfig:406:warning: ignoring unsupported character ','
'ernel/trace/Kconfig:406:warning: ignoring unsupported character '
kernel/trace/Kconfig:406: unknown option "kernel"
'ernel/trace/Kconfig:407:warning: ignoring unsupported character '
kernel/trace/Kconfig:407: unknown option "stack-trace"
'ernel/trace/Kconfig:408:warning: ignoring unsupported character '
kernel/trace/Kconfig:408: unknown option "then"
'ernel/trace/Kconfig:409:warning: ignoring unsupported character '
kernel/trace/Kconfig:409: unknown option "is"

How can I fix this error?

**Comment by fhqddm** [comment]
I tried “export CROSS_COMPILE=/usr/bin/aarch64-linux-gnu-”，and I couldn't get it right

**Comment by weissric** [comment]
NVIDIA recommends the Linaro 7.3.1 2018.05 cross compiler for compiling the l4t-r32.2.1 kernel. I first could not compile the kernel with my standard compiler. NVIDIA provides a reference toolchain in their [development guide](https://docs.nvidia.com/jetson/archives/l4t-archived/l4t-322/index.html#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/xavier_toolchain.html). 

However, the `make tegra18_hdmi2csi_defconfig` command does not need any compiler. Also make sure, the build-essential is installed correctly.

**Comment by fhqddm** [comment]
I tried the " Linaro 7.3.1 2018.05  cross compiler" and still reported the same error. I rechecked the integrity of the repository and found several error at the end:
error: unable to stat just-written file drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c: No such file or directory
error: unable to stat just-written file drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.h: No such file or directory
Submodule path 'kernel/nvgpu': checked out '2081ce686bfd4deb461b4130df424d592000ff88'
Submodule path 'kernel/nvidia': checked out '9c6789e8477ca112fbec2b85c2fde3aa5940b55a'
Unable to checkout '660291858457b620c60e0fec6c58aed6995853bb' in submodule path 'kernel/kernel-4.9'
Does this cause the compilation to fail？

**Comment by weissric** [comment]
It seems that your repository is still not checked out correctly. I would recommend to start from scratch and following the steps mentioned in my [previous post](https://github.com/InES-HPMM/linux-l4t-4.9/issues/3#issuecomment-553771150). Please ensure that you check out the submodules from the top directory of the repository.

After running the command `git submodule status --recursive`

The output should look like:
``` eeac15a2362b8ee55d2afc60839711f1d5d6244a hardware/nvidia/platform/t18x/common (heads/hdmi2csi/l4t-r32.2.1)
 6509ea9a0677063fac7e7936040cff6c47ddbcaa hardware/nvidia/platform/t18x/quill (heads/hdmi2csi/l4t-r32.2.1)
 29430727cfbc62b5ef6ed288dcedfcb01332091d hardware/nvidia/platform/t19x/common (heads/hdmi2csi/l4t-r32.2.1)
 279af4e3f9326bc6c96fedfaa97d25fe72cb82fa hardware/nvidia/platform/t19x/galen/bct (heads/hdmi2csi/l4t-r32.2.1)
 970bd5e2386fb7247989c1080e5a76c19f87f276 hardware/nvidia/platform/t19x/galen/kernel-dts (heads/hdmi2csi/l4t-r32.2.1)
 b47e62fbaa34800cc2e6f709be0fa4173e55600d hardware/nvidia/platform/t210/common (heads/hdmi2csi/l4t-r32.2.1)
 aa704972e4a6fbe4d306c9247bf6a455433e0cf6 hardware/nvidia/platform/t210/jetson (heads/hdmi2csi/l4t-r32.2.1)
 5157b93762c80f1731c0474bd975a80212af65e4 hardware/nvidia/platform/t210/porg (heads/hdmi2csi/l4t-r32.2.1)
 4bae6f73896636f484dedcb9c233d16032f1ab49 hardware/nvidia/platform/tegra/common (heads/hdmi2csi/l4t-r32.2.1)
 2592ac82d1f1ecb19af92427969ad4164a559031 hardware/nvidia/soc/t18x (heads/hdmi2csi/l4t-r32.2.1)
 216600efe9a85a1a848caa3e193c6ab7ef004a16 hardware/nvidia/soc/t19x (heads/hdmi2csi/l4t-r32.2.1)
 4df6a72522b57dc8a40643ecb1419eb31bd166a3 hardware/nvidia/soc/t210 (heads/hdmi2csi/l4t-r32.2.1)
 8c1adb4f4d1bfd07256d993e7b6c922e44ac4840 hardware/nvidia/soc/tegra (heads/hdmi2csi/l4t-r32.2.1)
+acc650c67cf30c7a5f01d596970ad37c6a65d69b kernel/kernel-4.9 (heads/hdmi2csi/l4t-r32.2.1)
 2081ce686bfd4deb461b4130df424d592000ff88 kernel/nvgpu (heads/hdmi2csi/l4t-r32.2.1)
 9c6789e8477ca112fbec2b85c2fde3aa5940b55a kernel/nvidia (heads/hdmi2csi/l4t-r32.2.1)```

**Comment by fhqddm** [comment]
I checked out again, and running the command  `git submodule status --recursive`:

 eeac15a2362b8ee55d2afc60839711f1d5d6244a hardware/nvidia/platform/t18x/common (heads/hdmi2csi/l4t-r32.2.1)
 6509ea9a0677063fac7e7936040cff6c47ddbcaa hardware/nvidia/platform/t18x/quill (heads/hdmi2csi/l4t-r32.2.1)
 29430727cfbc62b5ef6ed288dcedfcb01332091d hardware/nvidia/platform/t19x/common (heads/hdmi2csi/l4t-r32.2.1)
 279af4e3f9326bc6c96fedfaa97d25fe72cb82fa hardware/nvidia/platform/t19x/galen/bct (heads/hdmi2csi/l4t-r32.2.1)
 970bd5e2386fb7247989c1080e5a76c19f87f276 hardware/nvidia/platform/t19x/galen/kernel-dts (heads/hdmi2csi/l4t-r32.2.1)
 b47e62fbaa34800cc2e6f709be0fa4173e55600d hardware/nvidia/platform/t210/common (heads/hdmi2csi/l4t-r32.2.1)
 aa704972e4a6fbe4d306c9247bf6a455433e0cf6 hardware/nvidia/platform/t210/jetson (heads/hdmi2csi/l4t-r32.2.1)
 5157b93762c80f1731c0474bd975a80212af65e4 hardware/nvidia/platform/t210/porg (heads/hdmi2csi/l4t-r32.2.1)
 4bae6f73896636f484dedcb9c233d16032f1ab49 hardware/nvidia/platform/tegra/common (heads/hdmi2csi/l4t-r32.2.1)
 2592ac82d1f1ecb19af92427969ad4164a559031 hardware/nvidia/soc/t18x (heads/hdmi2csi/l4t-r32.2.1)
 216600efe9a85a1a848caa3e193c6ab7ef004a16 hardware/nvidia/soc/t19x (heads/hdmi2csi/l4t-r32.2.1)
 4df6a72522b57dc8a40643ecb1419eb31bd166a3 hardware/nvidia/soc/t210 (heads/hdmi2csi/l4t-r32.2.1)
 8c1adb4f4d1bfd07256d993e7b6c922e44ac4840 hardware/nvidia/soc/tegra (heads/hdmi2csi/l4t-r32.2.1)
 660291858457b620c60e0fec6c58aed6995853bb kernel/kernel-4.9 (660291858457)
 2081ce686bfd4deb461b4130df424d592000ff88 kernel/nvgpu (heads/hdmi2csi/l4t-r32.2.1)
 9c6789e8477ca112fbec2b85c2fde3aa5940b55a kernel/nvidia (heads/hdmi2csi/l4t-r32.2.1)

make tegra18_hdmi2csi_defconfig:
still a lot of error message "syntax error":
'ernel/trace/Kconfig:405⚠️ ignoring unsupported character '
kernel/trace/Kconfig:405: unknown option "This"
kernel/trace/Kconfig:406⚠️ ignoring unsupported character ','
'ernel/trace/Kconfig:406⚠️ ignoring unsupported character '
kernel/trace/Kconfig:406: unknown option "kernel"
'ernel/trace/Kconfig:407⚠️ ignoring unsupported character '
kernel/trace/Kconfig:407: unknown option "stack-trace"
'ernel/trace/Kconfig:408⚠️ ignoring unsupported character '
kernel/trace/Kconfig:408: unknown option "then"
'ernel/trace/Kconfig:409⚠️ ignoring unsupported character '
kernel/trace/Kconfig:409: unknown option "is"

**Comment by fhqddm** [comment]
I checked out again, and running the command  `git submodule status --recursive`:

 eeac15a2362b8ee55d2afc60839711f1d5d6244a hardware/nvidia/platform/t18x/common (heads/hdmi2csi/l4t-r32.2.1)
 6509ea9a0677063fac7e7936040cff6c47ddbcaa hardware/nvidia/platform/t18x/quill (heads/hdmi2csi/l4t-r32.2.1)
 29430727cfbc62b5ef6ed288dcedfcb01332091d hardware/nvidia/platform/t19x/common (heads/hdmi2csi/l4t-r32.2.1)
 279af4e3f9326bc6c96fedfaa97d25fe72cb82fa hardware/nvidia/platform/t19x/galen/bct (heads/hdmi2csi/l4t-r32.2.1)
 970bd5e2386fb7247989c1080e5a76c19f87f276 hardware/nvidia/platform/t19x/galen/kernel-dts (heads/hdmi2csi/l4t-r32.2.1)
 b47e62fbaa34800cc2e6f709be0fa4173e55600d hardware/nvidia/platform/t210/common (heads/hdmi2csi/l4t-r32.2.1)
 aa704972e4a6fbe4d306c9247bf6a455433e0cf6 hardware/nvidia/platform/t210/jetson (heads/hdmi2csi/l4t-r32.2.1)
 5157b93762c80f1731c0474bd975a80212af65e4 hardware/nvidia/platform/t210/porg (heads/hdmi2csi/l4t-r32.2.1)
 4bae6f73896636f484dedcb9c233d16032f1ab49 hardware/nvidia/platform/tegra/common (heads/hdmi2csi/l4t-r32.2.1)
 2592ac82d1f1ecb19af92427969ad4164a559031 hardware/nvidia/soc/t18x (heads/hdmi2csi/l4t-r32.2.1)
 216600efe9a85a1a848caa3e193c6ab7ef004a16 hardware/nvidia/soc/t19x (heads/hdmi2csi/l4t-r32.2.1)
 4df6a72522b57dc8a40643ecb1419eb31bd166a3 hardware/nvidia/soc/t210 (heads/hdmi2csi/l4t-r32.2.1)
 8c1adb4f4d1bfd07256d993e7b6c922e44ac4840 hardware/nvidia/soc/tegra (heads/hdmi2csi/l4t-r32.2.1)
 660291858457b620c60e0fec6c58aed6995853bb kernel/kernel-4.9 (660291858457)
 2081ce686bfd4deb461b4130df424d592000ff88 kernel/nvgpu (heads/hdmi2csi/l4t-r32.2.1)
 9c6789e8477ca112fbec2b85c2fde3aa5940b55a kernel/nvidia (heads/hdmi2csi/l4t-r32.2.1)

make tegra18_hdmi2csi_defconfig:
still a lot of error message "syntax error":
'ernel/trace/Kconfig:405⚠️ ignoring unsupported character '
kernel/trace/Kconfig:405: unknown option "This"
kernel/trace/Kconfig:406⚠️ ignoring unsupported character ','
'ernel/trace/Kconfig:406⚠️ ignoring unsupported character '
kernel/trace/Kconfig:406: unknown option "kernel"
'ernel/trace/Kconfig:407⚠️ ignoring unsupported character '
kernel/trace/Kconfig:407: unknown option "stack-trace"
'ernel/trace/Kconfig:408⚠️ ignoring unsupported character '
kernel/trace/Kconfig:408: unknown option "then"
'ernel/trace/Kconfig:409⚠️ ignoring unsupported character '
kernel/trace/Kconfig:409: unknown option "is"

**Comment by fhqddm** [comment]
These two outcomes are different：
yours:+acc650c67cf30c7a5f01d596970ad37c6a65d69b kernel/kernel-4.9 (heads/hdmi2csi/l4t-r32.2.1)
mine: 660291858457b620c60e0fec6c58aed6995853bb kernel/kernel-4.9 (660291858457)

**Comment by weissric** [comment]
I found, that a commit in the subrepo was not commited in the top repository. That's why the sub repository was on the wrong commit after cloning the repository.This has now been fixed.

However, This issue should have disappeared after checking out the branch of the subrepo. Note that you have to run this command in the top folder as it searches for submodules of the current repository.

Check out the branch hdmi2csi/l4t-r32.2.1:
git submodule foreach --recursive 'git checkout hdmi2csi/l4t-r32.2.1 || :'

**Comment by fhqddm** [comment]
'home/nv/package/linux-l4t-4.9/kernel/nvidia/arch/arm64/Kconfig:35:warning: ignoring unsupported character '
'home/nv/package/linux-l4t-4.9/kernel/nvidia/arch/arm64/Kconfig:36:warning: ignoring unsupported character '
'home/nv/package/linux-l4t-4.9/kernel/nvidia/arch/arm64/Kconfig:37:warning: ignoring unsupported character '
'home/nv/package/linux-l4t-4.9/kernel/nvidia/arch/arm64/Kconfig:38:warning: ignoring unsupported character '
'home/nv/package/linux-l4t-4.9/kernel/nvidia/arch/arm64/Kconfig:39:warning: ignoring unsupported character '
'home/nv/package/linux-l4t-4.9/kernel/nvidia/arch/arm64/Kconfig:40:warning: ignoring unsupported character '
'home/nv/package/linux-l4t-4.9/kernel/nvidia/arch/arm64/Kconfig:40:warning: ignoring unsupported character '
'home/nv/package/linux-l4t-4.9/kernel/nvidia/arch/arm64/Kconfig:44:warning: ignoring unsupported character '
scripts/kconfig/Makefile:37: recipe for target 'silentoldconfig' failed
make[2]: *** [silentoldconfig] Error 1
Makefile:565: recipe for target 'silentoldconfig' failed
make[1]: *** [silentoldconfig] Error 2
make: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.

**Comment by cizerpat** [comment]
Closed due to inactivity

**Comment by cizerpat** [comment]
Closed due to inactivity
