### ISSUE TITLE
No suitable SDK available anymore

### ISSUE THREAD

**Issue by pawosm-arm** [InES-HPMM/linux-l4t-4.9#5]
Hello,

I'd like to give HDMI2CSI a try on my Jetson TX2 board, but since it is 5 years too late for doing so, I'm facing problems with getting all the software I need.

First, my Jetson has the r28.1 software installed (JetPack 3.1) with the Linux kernel 4.4.38, so I'd like to upgrade it to the Linux 4.9 kernel first. This would require updating the installed software to the version r32.2.1 which is shipped with the JetPack 4.2.2. Sadly, this version of JetPack can only be downloaded by the SDK Manager. And here's the problem, JetPack versions older than 4.4 have been removed from nvidia servers and the SDK Managers that could download JetPack versions older than 4.4 (e.g. SDK Manager 1.6.1 that I have tried) are refusing to log in to the developer's account (`invalid_request Authorization flow not allowed`). I have no problem with logging in from SDK Manager 2.1.0, but this newer version can't download anything older than JetPack 4.4, even if I start it with the `--archivedversions` command-line option.

Do you have any suggestion on how could I try to upgrade my TX2 board?

**Comment by MichaelWaespe1** [comment]
Hi @pawosm-arm 

I'll have a look at it over the next few days. You could also upgrade to the latest L4T version supported by the TX2 and include the relevant HDMI2CSI sources like we did in this repo. However, we have never tried this so we cannot confirm that it works.

Best regards
Michael

**Comment by pawosm-arm** [comment]
Hi @MichaelWaespe1 I've managed to make this HDMI2CSI work with my Jetson TX2 eventually, but I haven't been doing any drastic upgrades as initially planned, I guess it wouldn't be possible these days. Anyways, since it works, I guess this ticket can be closed.
